package cli

import (
	"io"

	"github.com/bitbrew-dev/jevwise/internal/debuglog"
	"github.com/spf13/cobra"
)

// Instrument declared commands only. Help/completion generated by Cobra stay quiet.
func instrumentCommands(cmd *cobra.Command) {
	if run := cmd.RunE; run != nil {
		operation := cmd.CommandPath()
		cmd.RunE = func(cmd *cobra.Command, args []string) (err error) {
			previous := cmd.Context()
			var writer io.Writer
			if enabled, _ := cmd.Flags().GetBool("debug"); enabled {
				writer = cmd.ErrOrStderr()
			}
			cmd.SetContext(debuglog.WithWriter(previous, writer))
			defer cmd.SetContext(previous)
			finish := debuglog.Trace(cmd.Context(), operation)
			defer func() { finish(err) }()
			return run(cmd, args)
		}
	}
	for _, child := range cmd.Commands() {
		instrumentCommands(child)
	}
}
